baseURL: "https://davidisaksson.dev/"
title: "DIDEV"
theme: "PaperMod"
languageCode: "en-us"

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
