baseURL: "https://davidisaksson.dev/"
title: "~/.didev"
theme: "PaperMod"
languageCode: "en-us"

# See params: https://github.com/adityatelange/hugo-PaperMod/wiki/Features
params:
  author: David Isaksson
  showToc: false
  TocOpen: true
  ShowReadingTime: true
  ShowWordCount: false
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  SearchHidden: false
  ShowCodeCopyButtons: true

  editPost:
    URL: "https://github.com/Granddave/site/tree/main/content"
    Text: "Found a typo?"
    appendFilePath: true

  homeInfoParams:
    Title: Hi there, welcome to my space.
    Content: Here I post about my day to day discoveries in tech.
  socialIcons:
    - name: "Github"
      url: "https://github.com/granddave"
    - name: "X"
      url: "https://x.com/David_Isaksson"
    - name: "Linkedin"
      url: "https://www.linkedin.com/in/david-isaksson/"

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: About Me
          url: about/
          weight: 1
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 11
        - name: Archive
          url: archive/
          weight: 15
        # - name: Categories
        #   url: categories/
        #   weight: 15

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
