---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Hugo CI & Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.REMOTE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<EOF
          Host ${{ secrets.REMOTE_HOST }}
            IdentityFile ~/.ssh/id_ed25519
            User ${{ secrets.REMOTE_USER }}
          EOF

      # Build and deploy
      - name: Build website
        run: make
      - name: Deploy website
        run: make deploy
        env:
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}

      # Clean up
      - name: Clean up
        run: |
          rm -rf ~/.ssh/id_ed25519
          rm -rf ~/.ssh/known_hosts
          rm -rf ~/.ssh/config
          echo "Cleaned up SSH keys and config"
